FROM postgres:16-alpine

# Set environment variables for PostgreSQL
ENV POSTGRES_DB=${POSTGRES_DB}
ENV POSTGRES_USER=${POSTGRES_USER}
ENV POSTGRES_PASSWORD=${POSTGRES_PASSWORD}


# Expose PostgreSQL port
EXPOSE 5432

# Set default command
CMD ["postgres"]
