"""add_amenities_to_rooms

Revision ID: 2ba25ee72bd4
Revises: 3df067292fe2
Create Date: 2025-08-20 11:40:25.408047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ba25ee72bd4'
down_revision: Union[str, Sequence[str], None] = '3df067292fe2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('amenities', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'amenities')
    # ### end Alembic commands ###
