"""create_availability_table

Revision ID: 3df067292fe2
Revises: bcfaffb1773d
Create Date: 2025-08-20 11:14:26.825731

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3df067292fe2"
down_revision: Union[str, Sequence[str], None] = "bcfaffb1773d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "availability",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("room_id", sa.UUID(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("total_rooms", sa.Integer(), nullable=False, default=5),
        sa.Column("available_rooms", sa.Integer(), nullable=False, default=5),
        sa.Column("price_override", sa.Float(), nullable=True),
        sa.Column("is_blocked", sa.Boolean(), default=False, nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["rooms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    # Create unique constraint to prevent duplicate entries for same room and date
    op.create_index(
        "ix_availability_room_date", "availability", ["room_id", "date"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_availability_room_date", table_name="availability")
    op.drop_table("availability")
    # ### end Alembic commands ###
