"""update_existing_rooms_guest_to_4

Revision ID: 71560482c7e2
Revises: a53d152227c3
Create Date: 2025-08-20 19:31:51.919030

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "71560482c7e2"
down_revision: Union[str, Sequence[str], None] = "a53d152227c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Update all existing rooms to have guest = 4
    op.execute("UPDATE rooms SET guest = 4 WHERE guest = 1")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert all rooms back to guest = 1
    op.execute("UPDATE rooms SET guest = 1 WHERE guest = 4")
    # ### end Alembic commands ###
