"""add_guest_column_to_rooms

Revision ID: a53d152227c3
Revises: 06966db4514e
Create Date: 2025-08-20 19:26:02.028794

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a53d152227c3"
down_revision: Union[str, Sequence[str], None] = "06966db4514e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # First add the column as nullable
    op.add_column("rooms", sa.Column("guest", sa.Integer(), nullable=True))

    # Update existing rows with default value
    op.execute("UPDATE rooms SET guest = 4 WHERE guest IS NULL")

    # Then make it NOT NULL
    op.alter_column("rooms", "guest", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rooms", "guest")
    # ### end Alembic commands ###
